package com.chuangbang.js.vo;

import java.util.List;

import com.google.common.collect.Lists;

public class JsTree {

	private String id;// will be autogenerated if omitted
	private String 	  text;
	private String 	  icon;
	private String parent;
	private JsTreeState  state;
	private List<JsTree> 	  children = Lists.newArrayList();
	
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getIcon() {
		return icon;
	}
	public void setIcon(String icon) {
		this.icon = icon;
	}
	public JsTreeState getState() {
		return state;
	}
	public void setState(JsTreeState state) {
		this.state = state;
	}
	public List<JsTree> getChildren() {
		return children;
	}
	public void setChildren(List<JsTree> children) {
		this.children = children;
	}
	public String getParent() {
		return parent;
	}
	public void setParent(String parent) {
		this.parent = parent;
	}
	
	
}
